# Generated by Django 3.0.8 on 2020-07-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='', max_length=70),
        ),
    ]
