# Generated by Django 3.0.8 on 2020-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=2000)),
                ('profilepicture', models.ImageField(blank=True, upload_to='profile_picture/')),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
