# Generated by Django 3.0.8 on 2020-07-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='authUser',
        ),
    ]
